[2024-02-06T22:20:26.319+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-02-06T22:20:26.341+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-02-06T22:20:26.343+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T22:20:26.454+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-05 00:00:00+00:00
[2024-02-06T22:20:26.479+0100] {standard_task_runner.py:60} INFO - Started process 44887 to run task
[2024-02-06T22:20:26.513+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmpb4hkf17p']
[2024-02-06T22:20:26.520+0100] {standard_task_runner.py:88} INFO - Job 35: Subtask match_task
[2024-02-06T22:20:26.680+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-05T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T22:20:26.982+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-02-06T22:20:27.052+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T22:20:28.094+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T22:20:28.117+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T22:20:28.128+0100] {client.py:496} INFO - Writing to '/datalake/raw/2024-01-05'.
[2024-02-06T22:20:28.154+0100] {logging_mixin.py:188} INFO - Some error occurred during writing to hdfs: HTTPConnectionPool(host='localhost', port=9870): Max retries exceeded with url: /webhdfs/v1/datalake/raw/2024-01-05?user.name=ubuntu&overwrite=True&op=CREATE (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa672f4e500>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-06T22:20:28.155+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T22:20:28.298+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240105T000000, start_date=20240206T212026, end_date=20240206T212028
[2024-02-06T22:20:28.603+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T22:20:28.920+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-02-06T23:17:30.406+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-02-06T23:17:30.445+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-02-06T23:17:30.445+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T23:17:30.776+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-05 00:00:00+00:00
[2024-02-06T23:17:30.803+0100] {standard_task_runner.py:60} INFO - Started process 66295 to run task
[2024-02-06T23:17:30.812+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmpgyzih2e1']
[2024-02-06T23:17:30.816+0100] {standard_task_runner.py:88} INFO - Job 39: Subtask match_task
[2024-02-06T23:17:31.032+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-05T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T23:17:31.583+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-02-06T23:17:31.588+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T23:17:33.010+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T23:17:33.019+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T23:17:33.022+0100] {client.py:496} INFO - Writing to '/datalake/raw/match/2024-01-05.json'.
[2024-02-06T23:17:34.926+0100] {logging_mixin.py:188} INFO - téléversement vers HDFS réussi
[2024-02-06T23:17:34.928+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T23:17:34.974+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240105T000000, start_date=20240206T221730, end_date=20240206T221734
[2024-02-06T23:17:35.199+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T23:17:35.331+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
