[2024-02-06T22:16:21.285+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-06T22:16:21.303+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-06T22:16:21.304+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T22:16:21.480+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-01 00:00:00+00:00
[2024-02-06T22:16:21.495+0100] {standard_task_runner.py:60} INFO - Started process 41900 to run task
[2024-02-06T22:16:21.503+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmpkgzgf7z_']
[2024-02-06T22:16:21.507+0100] {standard_task_runner.py:88} INFO - Job 26: Subtask match_task
[2024-02-06T22:16:21.823+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-01T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T22:16:22.103+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-02-06T22:16:22.107+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T22:16:22.785+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T22:16:22.789+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T22:16:22.792+0100] {client.py:496} INFO - Writing to '/datalake/raw/2024-01-01'.
[2024-02-06T22:16:22.797+0100] {logging_mixin.py:188} INFO - Some error occurred during writing to hdfs: HTTPConnectionPool(host='localhost', port=9870): Max retries exceeded with url: /webhdfs/v1/datalake/raw/2024-01-01?user.name=ubuntu&overwrite=True&op=CREATE (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f53852530>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-06T22:16:22.798+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T22:16:22.809+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240101T000000, start_date=20240206T211621, end_date=20240206T211622
[2024-02-06T22:16:22.870+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T22:16:22.928+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-02-06T22:29:12.752+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-06T22:29:12.788+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-06T22:29:12.789+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T22:29:12.900+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-01 00:00:00+00:00
[2024-02-06T22:29:12.953+0100] {standard_task_runner.py:60} INFO - Started process 50958 to run task
[2024-02-06T22:29:12.961+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmppz6p2349']
[2024-02-06T22:29:12.979+0100] {standard_task_runner.py:88} INFO - Job 28: Subtask match_task
[2024-02-06T22:29:13.477+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-01T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T22:29:14.113+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-02-06T22:29:14.131+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T22:29:14.950+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T22:29:14.962+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T22:29:14.994+0100] {client.py:496} INFO - Writing to '/datalake/raw/2024-01-01'.
[2024-02-06T22:29:14.998+0100] {logging_mixin.py:188} INFO - Some error occurred during writing to hdfs: HTTPConnectionPool(host='localhost', port=9870): Max retries exceeded with url: /webhdfs/v1/datalake/raw/2024-01-01?user.name=ubuntu&overwrite=True&op=CREATE (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f95be2560>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-06T22:29:14.998+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T22:29:15.015+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240101T000000, start_date=20240206T212912, end_date=20240206T212915
[2024-02-06T22:29:15.237+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T22:29:15.407+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-02-06T23:31:38.803+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-06T23:31:38.835+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-06T23:31:38.836+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T23:31:38.971+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-01 00:00:00+00:00
[2024-02-06T23:31:39.001+0100] {standard_task_runner.py:60} INFO - Started process 73914 to run task
[2024-02-06T23:31:39.009+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmph44e76_p']
[2024-02-06T23:31:39.014+0100] {standard_task_runner.py:88} INFO - Job 41: Subtask match_task
[2024-02-06T23:31:39.356+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-01T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T23:31:39.826+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-02-06T23:31:39.836+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T23:31:40.967+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T23:31:40.975+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T23:31:40.980+0100] {client.py:496} INFO - Writing to '/datalake/raw/match/2024-01-01.json'.
[2024-02-06T23:31:43.386+0100] {logging_mixin.py:188} INFO - téléversement vers HDFS réussi
[2024-02-06T23:31:43.387+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T23:31:43.410+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240101T000000, start_date=20240206T223138, end_date=20240206T223143
[2024-02-06T23:31:43.715+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T23:31:43.880+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
