[2024-02-06T23:48:54.634+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.usageMatch_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-06T23:48:54.658+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.usageMatch_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-02-06T23:48:54.659+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T23:48:54.796+0100] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): usageMatch_task> on 2024-01-01 00:00:00+00:00
[2024-02-06T23:48:54.831+0100] {standard_task_runner.py:60} INFO - Started process 85008 to run task
[2024-02-06T23:48:54.850+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'usageMatch_task', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmpkkglgu8u']
[2024-02-06T23:48:54.857+0100] {standard_task_runner.py:88} INFO - Job 48: Subtask usageMatch_task
[2024-02-06T23:48:55.141+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.usageMatch_task scheduled__2024-01-01T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T23:48:55.627+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='usageMatch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-02-06T23:48:55.698+0100] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-02-06T23:48:55.707+0100] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master local[*] --conf spark.airflow.execution_date=2024-01-01 --name arrow-spark --class CombineData --queue root.default --deploy-mode client /home/ubuntu/airflow/scala/target/scala-2.13/scala_2.13-0.1.0.jar
[2024-02-06T23:48:55.993+0100] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 85008. PIDs of all processes in the group: [85030, 85008]
[2024-02-06T23:48:55.993+0100] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 85008
[2024-02-06T23:48:56.077+0100] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-06T23:48:56.095+0100] {process_utils.py:79} INFO - Process psutil.Process(pid=85030, status='terminated', started='23:48:54') (85030) terminated with exit code None
[2024-02-06T23:48:56.108+0100] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 490, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 539, in _process_spark_submit_log
    for line in itr:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-06T23:48:56.128+0100] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Competition_dag, task_id=usageMatch_task, execution_date=20240101T000000, start_date=20240206T224854, end_date=20240206T224856
[2024-02-06T23:48:56.452+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 48 for task usageMatch_task (Task received SIGTERM signal; 85008)
[2024-02-06T23:48:56.515+0100] {process_utils.py:79} INFO - Process psutil.Process(pid=85008, status='terminated', exitcode=1, started='23:48:53') (85008) terminated with exit code 1
