[2024-02-06T22:16:39.289+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-02-06T22:16:39.485+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-02-06T22:16:39.485+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T22:16:39.778+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-02 00:00:00+00:00
[2024-02-06T22:16:39.988+0100] {standard_task_runner.py:60} INFO - Started process 42092 to run task
[2024-02-06T22:16:40.068+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmp0fqu3ebd']
[2024-02-06T22:16:40.078+0100] {standard_task_runner.py:88} INFO - Job 27: Subtask match_task
[2024-02-06T22:16:40.615+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-02T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T22:16:40.979+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-02-06T22:16:41.170+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T22:16:42.032+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T22:16:42.036+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T22:16:42.044+0100] {client.py:496} INFO - Writing to '/datalake/raw/2024-01-02'.
[2024-02-06T22:16:42.049+0100] {logging_mixin.py:188} INFO - Some error occurred during writing to hdfs: HTTPConnectionPool(host='localhost', port=9870): Max retries exceeded with url: /webhdfs/v1/datalake/raw/2024-01-02?user.name=ubuntu&overwrite=True&op=CREATE (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6775bee500>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-06T22:16:42.054+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T22:16:42.100+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240102T000000, start_date=20240206T211639, end_date=20240206T211642
[2024-02-06T22:16:42.315+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T22:16:42.615+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-02-06T22:29:36.049+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-02-06T22:29:36.091+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-02-06T22:29:36.092+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T22:29:36.186+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-02 00:00:00+00:00
[2024-02-06T22:29:36.344+0100] {standard_task_runner.py:60} INFO - Started process 51225 to run task
[2024-02-06T22:29:36.390+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmprexnr405']
[2024-02-06T22:29:36.394+0100] {standard_task_runner.py:88} INFO - Job 29: Subtask match_task
[2024-02-06T22:29:36.676+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-02T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T22:29:37.594+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-02-06T22:29:37.598+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T22:29:38.978+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T22:29:38.992+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T22:29:38.995+0100] {client.py:496} INFO - Writing to '/datalake/raw/2024-01-02'.
[2024-02-06T22:29:39.001+0100] {logging_mixin.py:188} INFO - Some error occurred during writing to hdfs: HTTPConnectionPool(host='localhost', port=9870): Max retries exceeded with url: /webhdfs/v1/datalake/raw/2024-01-02?user.name=ubuntu&overwrite=True&op=CREATE (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e51096530>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-06T22:29:39.002+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T22:29:39.070+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240102T000000, start_date=20240206T212936, end_date=20240206T212939
[2024-02-06T22:29:39.356+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T22:29:39.681+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-02-06T23:33:17.830+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-02-06T23:33:17.894+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-02-06T23:33:17.903+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T23:33:17.989+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-02 00:00:00+00:00
[2024-02-06T23:33:18.012+0100] {standard_task_runner.py:60} INFO - Started process 75126 to run task
[2024-02-06T23:33:18.039+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmpxwyk5fp3']
[2024-02-06T23:33:18.043+0100] {standard_task_runner.py:88} INFO - Job 43: Subtask match_task
[2024-02-06T23:33:18.624+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-02T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T23:33:19.245+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-02-06T23:33:19.257+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T23:33:19.984+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T23:33:19.994+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T23:33:19.996+0100] {client.py:496} INFO - Writing to '/datalake/raw/match/2024-01-02.json'.
[2024-02-06T23:33:22.357+0100] {logging_mixin.py:188} INFO - téléversement vers HDFS réussi
[2024-02-06T23:33:22.359+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T23:33:22.377+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240102T000000, start_date=20240206T223317, end_date=20240206T223322
[2024-02-06T23:33:22.643+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T23:33:23.291+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
