[2024-02-06T22:19:55.504+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.cleanMatch_task manual__2024-02-06T21:16:29.651913+00:00 [queued]>
[2024-02-06T22:19:55.533+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.cleanMatch_task manual__2024-02-06T21:16:29.651913+00:00 [queued]>
[2024-02-06T22:19:55.534+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T22:19:55.650+0100] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): cleanMatch_task> on 2024-02-06 21:16:29.651913+00:00
[2024-02-06T22:19:55.672+0100] {standard_task_runner.py:60} INFO - Started process 44496 to run task
[2024-02-06T22:19:55.680+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'cleanMatch_task', 'manual__2024-02-06T21:16:29.651913+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmpxyuvrq6k']
[2024-02-06T22:19:55.685+0100] {standard_task_runner.py:88} INFO - Job 34: Subtask cleanMatch_task
[2024-02-06T22:19:55.929+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.cleanMatch_task manual__2024-02-06T21:16:29.651913+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T22:19:56.322+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='cleanMatch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T21:16:29.651913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T21:16:29.651913+00:00'
[2024-02-06T22:19:56.339+0100] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-02-06T22:19:56.343+0100] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.airflow.execution_date=2024-02-06 --name arrow-spark --class FormattedData --queue root.default /home/ubuntu/airflow/scala/target/scala-2.13/scala_2.13-0.1.0.jar
[2024-02-06T22:20:06.032+0100] {spark_submit.py:571} INFO - 24/02/06 22:20:05 WARN Utils: Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2024-02-06T22:20:06.036+0100] {spark_submit.py:571} INFO - 24/02/06 22:20:06 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-02-06T22:20:06.411+0100] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-02-06T22:20:06.416+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-02-06T22:20:06.417+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-02-06T22:20:06.418+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-02-06T22:20:06.419+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-02-06T22:20:06.419+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1055)
[2024-02-06T22:20:06.420+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1055)
[2024-02-06T22:20:06.436+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-02-06T22:20:06.437+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
[2024-02-06T22:20:06.437+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
[2024-02-06T22:20:06.463+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-02-06T22:20:06.590+0100] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.airflow.execution_date=2024-02-06 --name arrow-spark --class FormattedData --queue root.default /home/ubuntu/airflow/scala/target/scala-2.13/scala_2.13-0.1.0.jar. Error code is: 1.
[2024-02-06T22:20:06.608+0100] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Competition_dag, task_id=cleanMatch_task, execution_date=20240206T211629, start_date=20240206T211955, end_date=20240206T212006
[2024-02-06T22:20:06.750+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task cleanMatch_task (Cannot execute: spark-submit --master yarn --conf spark.airflow.execution_date=2024-02-06 --name arrow-spark --class FormattedData --queue root.default /home/ubuntu/airflow/scala/target/scala-2.13/scala_2.13-0.1.0.jar. Error code is: 1.; 44496)
[2024-02-06T22:20:06.773+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T22:20:06.844+0100] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
