[2024-02-06T22:18:01.761+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-02-06T22:18:01.789+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-02-06T22:18:01.791+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T22:18:02.064+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-03 00:00:00+00:00
[2024-02-06T22:18:02.135+0100] {standard_task_runner.py:60} INFO - Started process 43152 to run task
[2024-02-06T22:18:02.158+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmpzu8ykhhf']
[2024-02-06T22:18:02.173+0100] {standard_task_runner.py:88} INFO - Job 29: Subtask match_task
[2024-02-06T22:18:02.603+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-03T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T22:18:03.179+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-02-06T22:18:03.186+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T22:18:03.977+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T22:18:03.983+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T22:18:03.986+0100] {client.py:496} INFO - Writing to '/datalake/raw/2024-01-03'.
[2024-02-06T22:18:03.993+0100] {logging_mixin.py:188} INFO - Some error occurred during writing to hdfs: HTTPConnectionPool(host='localhost', port=9870): Max retries exceeded with url: /webhdfs/v1/datalake/raw/2024-01-03?user.name=ubuntu&overwrite=True&op=CREATE (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f233f5b2560>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-06T22:18:03.993+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T22:18:04.062+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240103T000000, start_date=20240206T211801, end_date=20240206T211804
[2024-02-06T22:18:04.218+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T22:18:04.269+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-02-06T22:31:38.043+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-02-06T22:31:38.101+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-02-06T22:31:38.105+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T22:31:38.291+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-03 00:00:00+00:00
[2024-02-06T22:31:38.372+0100] {standard_task_runner.py:60} INFO - Started process 52836 to run task
[2024-02-06T22:31:38.399+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmpeo61glqh']
[2024-02-06T22:31:38.414+0100] {standard_task_runner.py:88} INFO - Job 32: Subtask match_task
[2024-02-06T22:31:38.728+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-03T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T22:31:39.069+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-02-06T22:31:39.072+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T22:31:40.206+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T22:31:40.209+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T22:31:40.212+0100] {client.py:496} INFO - Writing to '/datalake/raw/2024-01-03'.
[2024-02-06T22:31:40.272+0100] {logging_mixin.py:188} INFO - Some error occurred during writing to hdfs: HTTPConnectionPool(host='localhost', port=9870): Max retries exceeded with url: /webhdfs/v1/datalake/raw/2024-01-03?user.name=ubuntu&overwrite=True&op=CREATE (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe25a02620>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-02-06T22:31:40.272+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T22:31:40.281+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240103T000000, start_date=20240206T213138, end_date=20240206T213140
[2024-02-06T22:31:40.459+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T22:31:40.613+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-02-06T23:45:15.570+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-02-06T23:45:15.689+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Competition_dag.match_task scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-02-06T23:45:15.690+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-06T23:45:15.952+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): match_task> on 2024-01-03 00:00:00+00:00
[2024-02-06T23:45:16.037+0100] {standard_task_runner.py:60} INFO - Started process 82322 to run task
[2024-02-06T23:45:16.043+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Competition_dag', 'match_task', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/datalake_dag.py', '--cfg-path', '/tmp/tmp50bvk9d7']
[2024-02-06T23:45:16.050+0100] {standard_task_runner.py:88} INFO - Job 46: Subtask match_task
[2024-02-06T23:45:16.458+0100] {task_command.py:423} INFO - Running <TaskInstance: Competition_dag.match_task scheduled__2024-01-03T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T23:45:17.318+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NOUMEN_Frech_Warren' AIRFLOW_CTX_DAG_ID='Competition_dag' AIRFLOW_CTX_TASK_ID='match_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-02-06T23:45:17.322+0100] {logging_mixin.py:188} INFO - helloWord
[2024-02-06T23:45:18.186+0100] {logging_mixin.py:188} INFO - Data fetch successfully
[2024-02-06T23:45:18.191+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-06T23:45:18.196+0100] {client.py:496} INFO - Writing to '/datalake/raw/match/2024-01-03.json'.
[2024-02-06T23:45:18.877+0100] {logging_mixin.py:188} INFO - téléversement vers HDFS réussi
[2024-02-06T23:45:18.878+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-06T23:45:18.888+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Competition_dag, task_id=match_task, execution_date=20240103T000000, start_date=20240206T224515, end_date=20240206T224518
[2024-02-06T23:45:19.089+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-06T23:45:19.182+0100] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
